version: 2.1

jobs:
  test-control-archivos:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          working_directory: src/controlArchvios/
          command: pip install -r requirements.txt
          name: Install requirements
      - run:
          working_directory: src/controlArchvios/
          command: pytest test/
          name: Test

workflows:
  main:
    jobs:
      - test-control-archivos
