version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install requirements
      - run:
          command: pytest test/
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
